#!/usr/bin/env python

import apfel

# activate some options
apfel.SetPerturbativeOrder(1);
apfel.SetNumberOfGrids(3);
apfel.SetGridParameters(1,130,3,1e-9);
apfel.SetGridParameters(2,60,5,1e-1);
apfel.SetGridParameters(3,20,5,8e-1);

# Initializes integrals on the grids
apfel.InitializeAPFEL();

S = 8e3**2
Q0 = 2.0**0.5
Qmin = 10
Qmax = 6e3
NMX  = 30

print "Luminosities at sqrt(S) = ", S**0.5," GeV:\n"
print "- gg luminosity "
    
for i in range(1,31):
    Q = Qmin * pow(Qmax/Qmin,(float)(i-1)/(float)(NMX-1));
    apfel.EvolveAPFEL(Q0,Q);
    print "MX = ", Q,"LUMI =",apfel.LUMI(0,0,S)

print ""
